{application,plug_cowboy,
             [{config_mtime,1774586914},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,plug,cowboy,
                             cowboy_telemetry,telemetry]},
              {description,"A Plug adapter for Cowboy"},
              {modules,['Elixir.Plug.Cowboy','Elixir.Plug.Cowboy.Conn',
                        'Elixir.Plug.Cowboy.Drainer',
                        'Elixir.Plug.Cowboy.Handler',
                        'Elixir.Plug.Cowboy.Translator']},
              {registered,[]},
              {vsn,"2.4.1"},
              {mod,{'Elixir.Plug.Cowboy',[]}}]}.
