{application,paginator,
             [{config_mtime,1774586914},
              {optional_applications,[postgrex]},
              {applications,[kernel,stdlib,elixir,logger,ecto,ecto_sql,
                             postgrex,plug_crypto]},
              {description,"Cursor based pagination for Elixir Ecto.\n"},
              {modules,['Elixir.Paginator','Elixir.Paginator.Config',
                        'Elixir.Paginator.Cursor',
                        'Elixir.Paginator.Ecto.Query','Elixir.Paginator.Page',
                        'Elixir.Paginator.Page.Metadata']},
              {registered,[]},
              {vsn,"1.0.4"}]}.
