{application,mail,
             [{config_mtime,1774586914},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"Easily build a composable mail message"},
              {modules,['Elixir.Mail','Elixir.Mail.Encoder',
                        'Elixir.Mail.Encoders.Base64',
                        'Elixir.Mail.Encoders.Binary',
                        'Elixir.Mail.Encoders.EightBit',
                        'Elixir.Mail.Encoders.QuotedPrintable',
                        'Elixir.Mail.Encoders.SevenBit','Elixir.Mail.MIME',
                        'Elixir.Mail.Message','Elixir.Mail.Parsers.RFC2822',
                        'Elixir.Mail.Proplist',
                        'Elixir.Mail.Renderers.RFC2822',
                        'Elixir.Mail.TestAssertions']},
              {registered,[]},
              {vsn,"0.2.2"}]}.
